name: $DOCKER_COMPOSE_LOCAL_NAME
services:
  backend:
    build: ../
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5435
      - DEBUG=1
      - SECRET_KEY=somethingsupersecret
      - ALLOWED_HOSTS=*
    depends_on:
      db:
        condition: service_healthy

  db:
    ports:
      - "5435:5432"
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=smart_parking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: